[package]
name = "chex"
version = "0.0.0"
edition = "2021"

[dependencies]
ariadne = "0.4.1"
arrayvec = "0.7.4"
bitvec = "1.0.1"
fst = "0.4.7"
itertools = "0.13.0"
tap = "1.0.1"
ustr = "1.0.0"

[build-dependencies]
csv = "1.3.0"
fst = "0.4.7"
